// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DeletedeleteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void deletedelete() {
    driver.get("https://mspbackups.com/AP/Default.aspx");
    driver.manage().window().setSize(new Dimension(868, 728));
    driver.switchTo().frame(0);
    js.executeScript("window.scrollTo(0,0)");
    driver.switchTo().defaultContent();
    driver.findElement(By.cssSelector(".navbar-toggler-icon")).click();
    driver.findElement(By.id("organization")).click();
    driver.findElement(By.linkText("Administrators")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mbs-table-grid_row:nth-child(2) .-isCtrl .col > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".mbs-table-grid_row:nth-child(3) .-isCtrl .col > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".mbs-table-grid_row:nth-child(6) .-isCtrl .col > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".mbs-table-grid_row:nth-child(7) .-isCtrl .col > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".mbs-table-grid_row:nth-child(7) .-isCtrl .col > span")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".mbs-tabset_item:nth-child(3) > .mbs-tabset_link")).click();
    driver.findElement(By.cssSelector(".ng-untouched:nth-child(2) .mbs-radio_label")).click();
    driver.findElement(By.cssSelector(".ng-input")).click();
    driver.findElement(By.id("a93a64826845-2")).click();
    driver.findElement(By.cssSelector(".col-3 .btn")).click();
    driver.findElement(By.cssSelector(".mbs-sidepanel_footer-col .btn-primary")).click();
    driver.findElement(By.id("abac991b9304-2")).click();
    driver.findElement(By.cssSelector(".col-3 .btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".col-3 .btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().frame(0);
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".span12 > .widget .widget-header-title")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.cssSelector(".navbar-toggler")).click();
    driver.findElement(By.cssSelector(".mbs-form-group > .ng-untouched:nth-child(1) .mbs-check_label")).click();
    driver.findElement(By.cssSelector(".ng-dirty > .mbs-check > .mbs-check_label")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mbs-table-grid_row:nth-child(1) .-isCtrl .col > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
