// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test2CreateAdminTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test2CreateAdmin() {
    driver.get("https://mspbackups.com/AP/Default.aspx");
    driver.manage().window().setSize(new Dimension(1366, 728));
    driver.switchTo().frame(0);
    js.executeScript("window.scrollTo(0,0)");
    driver.switchTo().defaultContent();
    driver.findElement(By.id("organization")).click();
    driver.findElement(By.linkText("Administrators")).click();
    driver.findElement(By.cssSelector(".-isBlock > .btn")).click();
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.id("firstName")).sendKeys("Admin 1");
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("lastName")).sendKeys("Admin 1");
    driver.findElement(By.id("myMailField")).click();
    driver.findElement(By.id("myMailField")).sendKeys("admin1@msp360.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("123123123");
    driver.findElement(By.cssSelector(".mbs-sidepanel_footer-col .btn-primary")).click();
    driver.findElement(By.cssSelector(".mbs-sidepanel_footer-col .btn-primary")).click();
    driver.findElement(By.cssSelector(".mbs-table-grid_row:nth-child(6) .-isCtrl .col > span")).click();
  }
}
