package ru.stqa.pft.sandbox;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import org.slf4j.impl.StaticLoggerBinder;
import org.openqa.selenium.remote.DesiredCapabilities;

public class Test4CreateanewAdminTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "C:\\Java test\\Selenium\\geckodriver.exe");
    DesiredCapabilities dcap = new DesiredCapabilities();
    dcap.setCapability("pageLoadStrategy", "normal");
    ChromeOptions opt = new ChromeOptions();
    opt.merge(dcap);
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test4CreateanewAdmin() {
    driver.get("https://mspbackups.com/Admin/Login.aspx?logoff=1&ref=Default.aspx");
    driver.manage().window().setSize(new Dimension(1133, 728));
    driver.findElement(By.id("txtLogin")).click();
    driver.findElement(By.id("txtLogin")).sendKeys("oleg.k@msp360.com");
    driver.findElement(By.id("txtPassword")).click();
    driver.findElement(By.id("txtPassword")).sendKeys("123");
    driver.findElement(By.id("btnLogin")).click();
    driver.switchTo().frame(0);
    js.executeScript("window.scrollTo(0,0)");
    driver.switchTo().defaultContent();
    driver.findElement(By.id("organization")).click();
    driver.findElement(By.linkText("Administrators")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mbs-table-grid_row:nth-child(1) .-isCtrl .col > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
